FROM python:3.12-slim

ADD requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

ADD main.py /var/server/main.py
ADD config.py /var/server/config.py
ADD .env /var/server/.env

ADD database var/server/database
ADD routes var/server/routes
ADD auth var/server/auth

WORKDIR "/var/server/"

CMD uvicorn --host 0.0.0.0 main:app
